a = input('digite augo:')
print('Qual e o tipo primitivo? {}'.format(type(a)))
print('só tem espaços? {}'.format(a.isspace()))
print('Ele é alfabético? {}'.format(a.isalpha()))
print('Ele é numerico? {}'.format(a.isalnum()))
print('Ele é alfanumerico? {}'.format(a.isalnum()))
print('Ele está em minúsculas? {}'.format(a.islower()))
print('Ele está em maiúsculas? {}'.format(a.isupper()))
print('Ele está capitalizada? {}'.format(a.istitle()))
